apiVersion: v1
kind: Pod
metadata:
  name: chard
spec:
  containers:
  - name: chard
    image: chard:local
    ports:
    - containerPort: 8080
    securityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: Localhost
        localhostProfile: /profiles/profile.json
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "64Mi"
        cpu: "20m"
  restartPolicy: Always